# Generated by Django 3.2 on 2021-04-24 23:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Zblog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoginUser',
        ),
        migrations.DeleteModel(
            name='PasswordReset',
        ),
        migrations.DeleteModel(
            name='RegisterUser',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(default='no comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='s.kamahjnr@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(default='No name', max_length=15),
        ),
    ]
