# Generated by Django 3.2 on 2021-04-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zblog', '0002_auto_20210424_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(default='Write your comments'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='Your-email', max_length=254),
        ),
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(default='username', max_length=15),
        ),
    ]
